"""add breakout_watchlist table

Revision ID: 45d84d35b8d7
Revises: a68a9ef66e95
Create Date: 2026-02-20 20:44:56.542030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45d84d35b8d7'
down_revision: Union[str, Sequence[str], None] = 'a68a9ef66e95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breakout_watchlist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('stage', sa.Enum('watching', 'ready', 'failed', 'triggered', name='watchlist_stage_enum'), nullable=False),
    sa.Column('consolidation_days', sa.Integer(), nullable=False),
    sa.Column('atr_ratio', sa.Float(), nullable=False),
    sa.Column('higher_lows', sa.Boolean(), nullable=False),
    sa.Column('near_10d_ma', sa.Boolean(), nullable=False),
    sa.Column('near_20d_ma', sa.Boolean(), nullable=False),
    sa.Column('volume_drying', sa.Boolean(), nullable=False),
    sa.Column('rs_composite', sa.Float(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('stage_changed_at', sa.DateTime(), nullable=False),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('breakout_watchlist', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_breakout_watchlist_ticker'), ['ticker'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('breakout_watchlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_breakout_watchlist_ticker'))

    op.drop_table('breakout_watchlist')
    # ### end Alembic commands ###
